### ISSUE TITLE
0.10-RC1: org.slf4j:slf4j-api missing from runtime classpath

### ISSUE THREAD

**Issue by davidburstrom** [ronmamo/reflections#336]
When bumping from 0.9.12 to 0.10-RC1, unit tests in my project starts failing due to missing `org.slf4j.LoggerFactory`. It would appear that `org:slf4j:slf4j-api` is not exposed in the runtime dependencies for the reflections library, though it is used internally.

```
java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at org.reflections.Reflections.<clinit>(Reflections.java:96)
```

It is of course possible to add `org:slf4j:slf4j-api` to the test runtime classpath in my consuming project as a workaround, but ultimately, this should be dictated by the reflections library.

**Comment by ronmamo** [comment]
thanks @davidburstrom , a fix pushed removing optional from slf4j-api dependency. hth, lmk

**Comment by ronmamo** [comment]
fixed on 0.10

**Comment by Gopro336** [comment]
getting this same issue on 0.10.2

**Comment by Gopro336** [comment]
and 0.10.1

**Comment by yelkhatib** [comment]
same issue on 0.11
